name: CI

# limit ci building to pushes to master not to get twice the notification email
# from github.
#
# if you want to test your branch on your fork, just replace the 'branches'
# filter below for 'push' with the one for 'pull_request' temporarily and drop
# the commit when creating the PR.
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: '*'

jobs:
  build:
    env:
      RUST_LOG: "interledger=trace"
      RUST_BACKTRACE: "full"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server redis-tools libssl-dev

      - name: Install rust toolchain
        uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable
          components: clippy, rustfmt

      - name: Build
        run: cargo build --all-features --all-targets

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Audit
        # FIXME: Disabled:
        # 1. spin: is no longer actively maintained
        # 2. sized-chunks: no safe upgrade.
        # 3. net2: has been removed from crates, still present as a dep to tokio
        run: cargo audit --ignore RUSTSEC-2019-0031 --ignore RUSTSEC-2020-0041 --ignore RUSTSEC-2020-0016

      - name: Test
        run: timeout 15m cargo test --all --all-features

      - name: Test with subset of features (interledger-packet)
        run: |
          timeout 15m cargo test -p interledger-packet
          timeout 15m cargo test -p interledger-packet --features strict
          timeout 15m cargo test -p interledger-packet --features roundtrip-only

      - name: Test with subset of features (interledger-btp)
        run: |
          timeout 15m cargo test -p interledger-btp
          timeout 15m cargo test -p interledger-btp --features strict

      - name: Test with subset of features (interledger-stream)
        run: |
          timeout 15m cargo test -p interledger-stream
          timeout 15m cargo test -p interledger-stream --features strict
          timeout 15m cargo test -p interledger-stream --features roundtrip-only

  test-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 'v12.18.4'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server redis-tools libssl-dev

          # install components (ganache-cli ilp-settlement-xrp conventional-changelog-cli)
          npm install -g ganache-cli ilp-settlement-xrp conventional-changelog-cli

      - name: Test
        run: |
          scripts/run-md-test.sh '^.*$' 1

      - name: 'Store artifacts'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: run-md-test
          path: /tmp/run-md-test

